server:
  port: 4000

spring:
  application:
    name: CLOUD-SERVER-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AshrafulalamRasel/cloud-config-server
          clone-on-start: true
